server:
  port: 8080

tickerSearcher:
  amadeus:
    app_config:
      url: https://test.api.amadeus.com/
      api_key: tp7ebwgBgGaGKxRcV1axHwU0kIRqLNlt
      api_secret: UAdoQJFlFKGDJaOj
    api:
      get_access_token: v1/security/oauth2/token
      shopping_flight_destinations: v1/shopping/flight-destinations
