server:
  port: 8080

tickerSearcher:
  amadeus:
    app:
      url: ${amadeus_app_url}
      api_key: ${amadeus_api_key}
      api_secret: ${amadeus_api_secret}
    api:
      get_access_token: ${amadeus_get_access_token}
      shopping_flight_destinations: ${amadeus_shopping_flight_destinations}
