server:
  port: 8080

flightTicketResource:
  amadeus:
    app_config:
      url: https://test.api.amadeus.com/
      api_key: {amadeus_api_key}
      api_secret: {amadeus_api_secret}
    api:
      get_access_token: v1/security/oauth2/token
      shopping_flight_destinations: v1/shopping/flight-destinations
