server:
  port: 8080
  servlet:
    context-path: /

airline_ticket_app:
  base_api_path: /api/v1

flightTicketResource:
  amadeus:
    app_config:
      url: ${amadeus_app_url}
      api_key: ${amadeus_api_key}
      api_secret: ${amadeus_api_secret}
    api:
      get_access_token: ${amadeus_get_access_token}
      shopping_flight_destinations: ${amadeus_shopping_flight_destinations}
